[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput --settings=slutton_backend.settings_production"
]

[start]
cmd = "daphne -b 0.0.0.0 -p $PORT slutton_backend.asgi:application"
