[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput --settings=slutton_backend.settings_production"
]

[start]
cmd = "gunicorn slutton_backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
