# Generated by Django 5.0.1 on 2025-10-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMemoryImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "theme",
                    models.CharField(
                        help_text="Daily theme (e.g., 'Lingerie & Lace', 'Red Hot Passion')",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "images",
                    models.JSONField(
                        default=list,
                        help_text="Array of 8 image URLs for the memory game",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Daily Memory Images",
                "ordering": ["-date"],
            },
        ),
    ]
