# Generated by Django 5.0.1 on 2025-10-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_dailymemoryimages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_url",
            field=models.CharField(
                help_text="URL or path to the game (e.g., /games/ouija or https://example.com)",
                max_length=500,
            ),
        ),
    ]
