# Generated by Django 5.2.7 on 2025-10-06 14:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyTrivia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=django.utils.timezone.now, unique=True),
                ),
                (
                    "theme",
                    models.CharField(
                        help_text="e.g., 'Seductive History', 'Pleasure Science'",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Daily Trivia Games",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="TriviaGameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "time_taken_seconds",
                    models.IntegerField(
                        default=0, help_text="Total time taken in seconds"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "daily_trivia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="trivia.dailytrivia",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trivia_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "time_taken_seconds"],
                "unique_together": {("user", "daily_trivia")},
            },
        ),
        migrations.CreateModel(
            name="TriviaQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(help_text="The witty, sensual question"),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("fill_blank", "Fill in the Blank"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("option_a", models.CharField(blank=True, max_length=200)),
                ("option_b", models.CharField(blank=True, max_length=200)),
                ("option_c", models.CharField(blank=True, max_length=200)),
                ("option_d", models.CharField(blank=True, max_length=200)),
                (
                    "correct_answer",
                    models.CharField(help_text="The correct answer", max_length=200),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Witty explanation after answering"
                    ),
                ),
                ("points_easy", models.IntegerField(default=10)),
                ("points_medium", models.IntegerField(default=20)),
                ("points_hard", models.IntegerField(default=30)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Question order in the game"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "daily_trivia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="trivia.dailytrivia",
                    ),
                ),
            ],
            options={
                "ordering": ["daily_trivia", "order"],
            },
        ),
        migrations.CreateModel(
            name="TriviaAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.CharField(max_length=200)),
                ("is_correct", models.BooleanField(default=False)),
                ("points_earned", models.IntegerField(default=0)),
                (
                    "time_taken_seconds",
                    models.IntegerField(
                        default=0, help_text="Time taken to answer this question"
                    ),
                ),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="trivia.triviagamesession",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="trivia.triviaquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["answered_at"],
            },
        ),
        migrations.CreateModel(
            name="UserTriviaStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_games_played", models.IntegerField(default=0)),
                ("total_points_earned", models.IntegerField(default=0)),
                ("first_place_finishes", models.IntegerField(default=0)),
                ("second_place_finishes", models.IntegerField(default=0)),
                ("third_place_finishes", models.IntegerField(default=0)),
                (
                    "available_points",
                    models.IntegerField(
                        default=0, help_text="Points available for discounts"
                    ),
                ),
                (
                    "current_streak",
                    models.IntegerField(default=0, help_text="Consecutive days played"),
                ),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_played_date", models.DateField(blank=True, null=True)),
                (
                    "perfect_games",
                    models.IntegerField(
                        default=0, help_text="Games with 100% correct answers"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trivia_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Trivia Stats",
            },
        ),
    ]
