# Generated by Django 5.2.7 on 2025-10-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trivia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="triviaquestion",
            name="options",
            field=models.JSONField(
                blank=True,
                help_text="Options as JSON: {'A': 'text', 'B': 'text', ...}",
                null=True,
            ),
        ),
    ]
