# Generated by Django 5.0.1 on 2025-10-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productrating",
            name="review",
            field=models.TextField(blank=True, help_text="Written review (optional)"),
        ),
    ]
